---
- name: ALTERNATIVES | Set commons
  community.general.alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  loop:
    - name: "awk"
      path: "{{ dbs_alternative_awk }}"
    - name: "editor"
      path: "{{ dbs_alternative_editor }}"

- name: COPY | dotfiles for root
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/root/.{{ item }}"
    mode: 0640
    owner: root
    group: root
  with_items:
    - "bashrc"
    - "vimrc"
  when: dbs_use_dotfiles

- name: SYSCTL | Tuning
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/ansible.conf
    state: present
  with_dict: "{{ dbs_sysctl_config }}"
  when: not dbs_is_docker

- name: COPY | Configure SSH
  ansible.builtin.copy:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
    owner: root
    group: root

- name: COPY | Configure vnstat
  ansible.builtin.copy:
    src: etc/vnstat.conf
    dest: /etc/vnstat.conf
    mode: 0644
    owner: root
    group: vnstat

- name: COPY | Configure bashrc
  ansible.builtin.copy:
    src: etc/skel/.bashrc
    dest: /etc/skel/.bashrc
    mode: 0644
    owner: root
    group: root

- name: COPY | Configure vimrc
  ansible.builtin.copy:
    src: etc/skel/.vimrc
    dest: /etc/skel/.vimrc
    mode: 0644
    owner: root
    group: root

- name: COPY | Configure Docker daemon
  ansible.builtin.copy:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root

- name: TEMPLATE | Configure zabbix_agent2
  ansible.builtin.template:
    src: etc/zabbix/zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    mode: 0644
    owner: root
    group: root

- name: RESTART | Services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ dbs_restart_services }}"
