" {{ ansible_managed }}
syntax on
set nu
set cursorline
set autoindent
set smartindent
set history=5000
set incsearch
set hlsearch
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set smarttab
filetype plugin on
